version: '3.9'
services:
  web:
    build: .
    image: my_web:1.0
    container_name: web
    command: python3 manage.py runserver 0.0.0.0:8080
    ports:
      - "8080:8080"
    volumes:
      - ./orders_website:/usr/src/orders_website
    depends_on: 
      - db
    networks:
      - my_network
  script:
    image: my_web:1.0
    container_name: script
    command: python3 single/scripts/single/orders_details_script.py
    volumes:
      - ./orders_website:/usr/src/orders_website
    depends_on: 
      - db
      - web
    networks:
      - my_network
      
  db:
    image: postgres:15.2-alpine
    container_name: db
    volumes:
      - ./pgdb:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=123321
      - POSTGRES_USER=postgres
      - POSTGRES_DB=orders_db
    ports:
      - "5432:5432"
    networks:
      - my_network
volumes:
  pgdb:

networks:
  my_network: