# Generated by Django 4.1.7 on 2023-03-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('order_number', models.IntegerField(unique=True)),
                ('price_usd', models.IntegerField()),
                ('delivery_time', models.DateField()),
                ('price_rub', models.IntegerField()),
            ],
        ),
    ]
